
CREATE TABLE QUESTIONS ( 
   ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
   QUESTION VARCHAR(500) NOT NULL, 
   MAXRATE DECIMAL(2,2) NOT NULL 
   /* USER_ID */
);


CREATE TABLE ANSWERS ( 
   ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
   ANSWER VARCHAR(500) NOT NULL, 
   RATE DECIMAL(2,2),
   QUESTION_ID BIGINT NOT NULL,
   FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS (ID)
   /* USER_ID */
);

/* CREATE TABLE USERS_TYPES ( 
   ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
   USER_TYPE VARCHAR(255) NOT NULL, 
);

CREATE TABLE USERS ( 
   ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
   NAME VARCHAR(255) NOT NULL, 
   TYPE_ID INT NOT NULL,
   FOREIGN KEY (TYPE_ID) REFERENCES USERS_TYPES (ID)
); */

COMMIT;